name:                familytree
version:             0.1.0.0
github:              "gcollic/familytree"
license:             AGPL-3
author:              "Guillaume COLLIC"
maintainer:          "gcollic@gmail.com"
copyright:           "2020 Guillaume COLLIC"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gcollic/familytree#readme>

dependencies:
- base >= 4.7 && < 5
- text
- megaparsec

library:
  source-dirs: src
  dependencies:
    - text
    - megaparsec
    - containers

executables:
  familytree-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwarn-incomplete-patterns
    dependencies:
    - familytree
    - text
    - megaparsec

tests:
  familytree-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - familytree
    - hspec
    - QuickCheck
    - hspec-megaparsec
    - megaparsec
